# Generated by Django 4.1.9 on 2023-06-23 17:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_resume"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resume",
            old_name="phone",
            new_name="phone_number",
        ),
    ]
